### ISSUE TITLE
python rescale.py error

### ISSUE THREAD

**Issue by leeivan1007** [BrunoVox/ScSR#4]
When I run
`python rescale.py
`
It appeared 
```
Traceback (most recent call last):
  File "rescale.py", line 19, in <module>
    imsave('{}{}'.format(train_lr_path, img_name), new_img, quality=100)
  File "/home/ros/anaconda3/envs/jetson_nano/lib/python3.7/site-packages/skimage/io/_io.py", line 131, in imsave
    return call_plugin('imsave', fname, arr, plugin=plugin, **plugin_args)
  File "/home/ros/anaconda3/envs/jetson_nano/lib/python3.7/site-packages/skimage/io/manage_plugins.py", line 210, in call_plugin
    return func(*args, **kwargs)
  File "/home/ros/anaconda3/envs/jetson_nano/lib/python3.7/site-packages/imageio/core/functions.py", line 303, in imwrite
    writer = get_writer(uri, format, "i", **kwargs)
  File "/home/ros/anaconda3/envs/jetson_nano/lib/python3.7/site-packages/imageio/core/functions.py", line 231, in get_writer
    return format.get_writer(request)
  File "/home/ros/anaconda3/envs/jetson_nano/lib/python3.7/site-packages/imageio/core/format.py", line 185, in get_writer
    return self.Writer(self, request)
  File "/home/ros/anaconda3/envs/jetson_nano/lib/python3.7/site-packages/imageio/core/format.py", line 221, in __init__
    self._open(**self.request.kwargs.copy())
TypeError: _open() got an unexpected keyword argument 'quality'
```
The skimage version is **'0.16.2'**. I though it is not match the right version.

**Comment by MingqiangNing** [comment]
When saving a JPEG, the compression ratio may be controlled using the
    ``quality`` keyword argument which is an integer with values in [1, 100]
    where 1 is worst quality and smallest file size, and 100 is best quality
    and largest file size (default 75).  This is only available when using
    the PIL and imageio plugins.


if your images are bmp format, delete quality is OK.
